[workspace]
members = ["ds5"]
resolver = "2"

[package]
name = "jaka-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "jaka-cli"
path = "src/bin/jaka_cli.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11.11"
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt", "macros", "rt-multi-thread", "signal", "time", "net", "io-util", "sync"] }

[build-dependencies]
cc = "1.4.4"
