//! Command line definitions using clap derive.
//!
//! Help is not generated by clap. It is printed from src/help.txt (see main.rs).

use std::path::PathBuf;

use clap::{Parser, Subcommand};

/// JAKA robotic arm driver
#[derive(Parser, Debug)]
#[command(
    name = "jaka-cli",
    version,
    about,
    long_about = None,
    disable_help_flag = true,
    disable_version_flag = true,
    disable_help_subcommand = true,
)]
pub struct Cli {
    /// Controller IP address
    #[arg(long, default_value = "10.5.5.100")]
    pub ip: String,

    /// Print the plan without connecting
    #[arg(long)]
    pub dry_run: bool,

    /// Show help, the content comes from src/help.txt
    #[arg(long, short = 'h')]
    pub help: bool,

    #[command(subcommand)]
    pub command: Option<Command>,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Read robot state: estop, power, enable, joint angles
    #[command(disable_help_flag = true)]
    Status,

    /// Power on and enable the robot to hold position
    #[command(disable_help_flag = true)]
    PowerOn,

    /// Disable servos and power off
    #[command(disable_help_flag = true)]
    PowerOff,

    /// Clear the e-stop error state, release the physical button first
    #[command(disable_help_flag = true)]
    EstopClear,

    /// Print the joint angles in degrees as JSON to stdout
    #[command(disable_help_flag = true)]
    Inspect,

    /// Power on, enable, then rotate the specified joint
    /// Rotate the specified joint
    #[command(disable_help_flag = true)]
    Rot {
        /// Joint to rotate, from 1 to 6
        #[arg(long, default_value_t = 6, value_parser = clap::value_parser!(i32).range(1..=6))]
        joint: i32,

        /// Rotation angle in degrees, negative reverses direction
        #[arg(long, default_value_t = 360.0, allow_negative_numbers = true)]
        deg: f64,

        /// Joint speed in radians per second
        #[arg(long, default_value_t = 0.8)]
        speed: f64,
    },

    /// Restore the joint angles recorded by inspect from a JSON file
    #[command(disable_help_flag = true)]
    Restore {
        /// Path to the JSON file produced by inspect
        #[arg(value_name = "JSON_FILE")]
        file: PathBuf,

        /// Joint speed in radians per second
        #[arg(long, default_value_t = 0.8)]
        speed: f64,
    },
}
