//! Command line definitions using clap derive.
//!
//! Help is not generated by clap. It is printed from src/bin/jaka_cli_help.txt (see main.rs).

use std::path::PathBuf;

use clap::{Parser, Subcommand, ValueEnum};

/// The IO bank to address, the end tool or the control cabinet
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum IoWhere {
    Tool,
    Cabinet,
}

/// The TIO pin bank to configure
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum TioPinBank {
    Di,
    Do,
    Ai,
}

/// A digital state word, accepts on/off
#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum OnOff {
    On,
    Off,
}

/// JAKA robotic arm driver
#[derive(Parser, Debug)]
#[command(
    name = "jaka-cli",
    version,
    about,
    long_about = None,
    disable_help_flag = true,
    disable_version_flag = true,
    disable_help_subcommand = true,
)]
pub struct Cli {
    /// Controller IP address
    #[arg(long, default_value = "10.5.5.100")]
    pub ip: String,

    /// Print the plan without connecting
    #[arg(long)]
    pub dry_run: bool,

    /// Show help, the content comes from src/help.txt
    #[arg(long, short = 'h')]
    pub help: bool,

    /// Run several commands in one connected session. Each value is a whole
    /// command line as it would follow jaka-cli, for example
    /// --sequence "move-to 100 0 0 --rel" "status"
    #[arg(long, value_name = "CMD", num_args = 1.., action = clap::ArgAction::Append)]
    pub sequence: Vec<String>,

    #[command(subcommand)]
    pub command: Option<Command>,
}

#[derive(Subcommand, Debug)]
pub enum Command {
    /// Read robot state: estop, power, enable, joint angles
    #[command(disable_help_flag = true)]
    Status,

    /// Power on and enable the robot to hold position
    #[command(disable_help_flag = true)]
    PowerOn,

    /// Enable the servos to hold position, robot must be powered
    #[command(disable_help_flag = true)]
    Enable,

    /// Disable the servos, the robot goes limp but stays powered
    #[command(disable_help_flag = true)]
    Disable,

    /// Disable servos and power off
    #[command(disable_help_flag = true)]
    PowerOff,

    /// Clear the e-stop error state, release the physical button first
    #[command(disable_help_flag = true)]
    EstopClear,

    /// Print the joint angles in degrees as JSON to stdout
    #[command(disable_help_flag = true)]
    Inspect,

    /// Print the TCP position relative to the base as JSON to stdout
    #[command(disable_help_flag = true)]
    InspectPos,

    /// Print the DH parameters as JSON to stdout
    #[command(disable_help_flag = true)]
    Dh,

    /// Power on, enable, then rotate the specified joint
    /// Rotate the specified joint
    #[command(disable_help_flag = true)]
    Rot {
        /// Joint to rotate, from 1 to 6
        #[arg(long, default_value_t = 6, value_parser = clap::value_parser!(i32).range(1..=6))]
        joint: i32,

        /// Rotation angle in degrees, negative reverses direction
        #[arg(long, default_value_t = 360.0, allow_negative_numbers = true)]
        deg: f64,

        /// Joint speed in radians per second
        #[arg(long, default_value_t = 0.8)]
        speed: f64,
    },

    /// Restore the joint angles recorded by inspect from a JSON file.
    /// Without a file the built-in default pose is used
    #[command(disable_help_flag = true)]
    Restore {
        /// Path to the JSON file produced by inspect, defaults to the built-in pose
        #[arg(value_name = "JSON_FILE")]
        file: Option<PathBuf>,

        /// Joint speed in radians per second
        #[arg(long, default_value_t = 100.0)]
        speed: f64,
    },

    /// Move the TCP to an absolute base-frame position, or with --rel to a
    /// position relative to the base pose. Repeating the same command is a
    /// no-op once the robot is already there
    #[command(disable_help_flag = true)]
    MoveTo {
        /// X coordinate in mm in the base frame
        #[arg(value_name = "X", allow_negative_numbers = true)]
        x: Option<f64>,

        /// Y coordinate in mm in the base frame
        #[arg(value_name = "Y", allow_negative_numbers = true)]
        y: Option<f64>,

        /// Z coordinate in mm in the base frame
        #[arg(value_name = "Z", allow_negative_numbers = true)]
        z: Option<f64>,

        /// Linear speed in mm/s
        #[arg(long, default_value_t = 100.0)]
        speed: f64,

        /// Treat x y z as offsets from the base pose instead of absolute coordinates
        #[arg(long)]
        rel: bool,

        /// Read the absolute target pose from an inspect-pos JSON file, position and orientation together
        #[arg(long, value_name = "POSE_FILE", conflicts_with_all = ["x", "y", "z"])]
        pose: Option<PathBuf>,

        /// The absolute target pose as an inspect-pos JSON string, position and orientation together
        #[arg(long, value_name = "JSON", conflicts_with_all = ["x", "y", "z", "pose"])]
        json: Option<String>,

        /// Target roll in degrees in the base frame, keep current when omitted
        #[arg(long, allow_negative_numbers = true)]
        rx: Option<f64>,

        /// Target pitch in degrees in the base frame, keep current when omitted
        #[arg(long, allow_negative_numbers = true)]
        ry: Option<f64>,

        /// Target yaw in degrees in the base frame, keep current when omitted
        #[arg(long, allow_negative_numbers = true)]
        rz: Option<f64>,
    },

    /// Move the TCP along a rising arc from the current pose to a base-frame
    /// point. The path peaks apex mm above the straight line, so a carried
    /// load clears the table on the way, and ends exactly on the point
    #[command(disable_help_flag = true)]
    Arc {
        /// X coordinate in mm in the base frame
        #[arg(value_name = "X", allow_negative_numbers = true)]
        x: f64,

        /// Y coordinate in mm in the base frame
        #[arg(value_name = "Y", allow_negative_numbers = true)]
        y: f64,

        /// Z coordinate in mm in the base frame
        #[arg(value_name = "Z", allow_negative_numbers = true)]
        z: f64,

        /// Rise of the arc peak above the straight start-to-end line in mm
        #[arg(long, default_value_t = 60.0, allow_negative_numbers = true)]
        apex: f64,

        /// Linear speed in mm/s
        #[arg(long, default_value_t = 100.0)]
        speed: f64,

        /// Treat x y z as offsets from the base pose instead of absolute coordinates
        #[arg(long)]
        rel: bool,
    },

    /// Move the TCP to an absolute base-frame point, or with --rel to a
    /// position relative to the base pose. The whole pick is one continuous
    /// servo motion: it rises from the current pose to hover over the source
    /// block, probes down and grabs it, carries it in an arc to hover over
    /// the target, probes down to seat it, releases the suction and lifts
    /// away, with no stop between the motions
    #[command(disable_help_flag = true)]
    Grab {
        /// Source block X offset in mm in the base frame
        #[arg(value_name = "FROM_X", allow_negative_numbers = true)]
        fromx: f64,
        /// Source block Y offset in mm
        #[arg(value_name = "FROM_Y", allow_negative_numbers = true)]
        fromy: f64,
        /// Target X offset in mm
        #[arg(value_name = "TO_X", allow_negative_numbers = true)]
        tox: f64,
        /// Target Y offset in mm
        #[arg(value_name = "TO_Y", allow_negative_numbers = true)]
        toy: f64,
        /// Rise of the carry arc above the straight line in mm
        #[arg(long, default_value_t = 80.0, allow_negative_numbers = true)]
        apex: f64,
        /// Linear speed in mm/s, the servo caps it itself
        #[arg(long, default_value_t = 2000.0)]
        speed: f64,
        /// Treat the offsets as relative to the base pose
        #[arg(long)]
        rel: bool,
    },

    /// Save the current TCP position as the base pose for move-to
    #[command(disable_help_flag = true)]
    SetBase,

    /// Serve a TCP control protocol for a gamepad. Incremental motion
    /// commands abort the previous motion and start a new one
    #[command(disable_help_flag = true)]
    Serve {
        /// TCP port to listen on
        #[arg(long, default_value_t = 5533)]
        port: u16,

        /// Run without a controller, print the commands and reply with a
        /// simulated state for testing the client side
        #[arg(long)]
        mock: bool,
    },

    /// Print every tool and cabinet digital input and output plus the tool
    /// IO supply voltage as JSON to stdout
    #[command(disable_help_flag = true)]
    IoState,

    /// Read one digital input of the tool or the cabinet
    #[command(disable_help_flag = true)]
    Di {
        /// The IO bank: tool or cabinet
        #[arg(value_enum, value_name = "TOOL|CABINET")]
        io_where: IoWhere,

        /// Input index, from 0
        #[arg(value_name = "INDEX")]
        index: i32,
    },

    /// Set one digital output of the tool or the cabinet and read it back
    #[command(disable_help_flag = true)]
    Do {
        /// The IO bank: tool or cabinet
        #[arg(value_enum, value_name = "TOOL|CABINET")]
        io_where: IoWhere,

        /// Output index, from 0
        #[arg(value_name = "INDEX")]
        index: i32,

        /// The new state: on or off
        #[arg(value_enum, value_name = "ON|OFF")]
        state: OnOff,
    },

    /// Show the tool IO supply voltage, or set it when a mode is given:
    /// 24 for 24 V, 12 for 12 V, off to disable the supply
    #[command(disable_help_flag = true)]
    TioVout {
        /// The supply mode: 24, 12 or off, query when omitted
        #[arg(value_name = "24|12|OFF", value_parser = ["24", "12", "off"])]
        mode: Option<String>,
    },

    /// Configure the TIO pin roles. The mode is a hex byte or a name: npn,
    /// pnp, push-pull (DO only), rs485 (DO = both channels, AI = RS485L) or
    /// analog (AI only). The raw hex byte is accepted as well: DO pins 0x0
    /// NPN, 0x1 PNP, 0x2 push-pull, 0xF RS485, the low nibble is DO1 and the
    /// high nibble DO2. AI pins 0 = analog, 1 = RS485L. DI pins pack two
    /// NPN/PNP bits per channel. Omit the mode to query
    ///
    /// The controller silently ignores the change while the servos are
    /// enabled: disable the robot first, configure, then enable again
    #[command(disable_help_flag = true)]
    TioPin {
        /// The pin bank: di, do or ai
        #[arg(value_enum, value_name = "DI|DO|AI")]
        bank: TioPinBank,

        /// The new mode as a hex byte, query when omitted
        #[arg(value_name = "HEX")]
        mode: Option<String>,
    },
}

/// A minimal CLI wrapper used to re-parse one command line of a --sequence.
/// The global options are ignored, only the subcommand is taken
#[derive(Parser, Debug)]
#[command(
    name = "jaka-cli",
    disable_help_flag = true,
    disable_version_flag = true
)]
pub struct SeqCommand {
    #[command(subcommand)]
    pub command: Option<Command>,
}
